server.port=8089
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anhvu08032004@gmail.com
spring.mail.password=odibojcrichowzle
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
# 0: no wait for kafka response
# 1: leader write success, not wait for follower
# -1: wait for all leader, and replication
spring.kafka.producer.acks=-1
spring.kafka.producer.enable-idempotence=true
spring.kafka.producer.retries=1
spring.kafka.producer.properties.request.timeout.ms=2000
spring.kafka.producer.properties.delivery.timeout.ms=3000

#prevent duplicate send
spring.kafka.producer.properties.[max.in.flight.requests.per.connection]=5