server.port=${SERVER_PORT:8084}
server.servlet.context-path=/

# Redis Connection
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}

# Resilience4J Circuit Breaker
resilience4j.circuitbreaker.instances.CircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.CircuitBreaker.permittedNumberOfCallsInHalfOpenState=5
resilience4j.circuitbreaker.instances.CircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.CircuitBreaker.waitDurationInOpenState=10000

# Resilience4J Time Limiter
resilience4j.timelimiter.instances.CircuitBreaker.timeoutDuration=3s
