server.port=${SERVER_PORT:8091}
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
UPLOAD_BASE_DIR=./uploads
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
