spring.application.name=StreamingService
spring.config.import=configserver:http://localhost:8082
spring.cloud.config.fail-fast=true
UPLOAD_BASE_DIR = C:\Users\vuna1\Desktop\learniverse\learniverse\StreamingService\src\main\java\com\example\StreamingService
