version: '3.8'

services:
  categoryservice:
    build: .
    restart: on-failure
    ports:
      - "8094:8094"
    env_file:
      - .env
    networks:
      - microservice-net

networks:
  microservice-net:
    external: true