services:
  mysql:
    image: mysql:latest  # <--- Updated to fetch the latest version
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - microservice-net

volumes:
  mysql_data:

networks:
  microservice-net:
    name: microservice-net
    external: true